### ISSUE TITLE
Balance Amount does not reflect the actual balance

### ISSUE THREAD

**Issue by Minal2179** [chiseledCoder/nikhilshirsath#14]
![image](https://user-images.githubusercontent.com/10168623/37989073-4b9c2872-31b7-11e8-8781-1fb2b047aa6c.png)

**Comment by chiseledCoder-zz** [comment]
Basically, it is to show how much balance amount of that particular invoice is outstanding if record payment is partially done.

**Comment by chiseledCoder-zz** [comment]
The invoice is of 20000 and you recorded the payment of 20000 so balance amount 0

**Comment by Minal2179** [comment]
ok understood, but could be confusing to the user, so hover msg can be made

**Comment by chiseledCoder-zz** [comment]
Close this if the issue is fixed.

**Comment by Minal2179** [comment]
tested and works fine
