### ISSUE TITLE
placement of project details button can be changed

### ISSUE THREAD

**Issue by Minal2179** [chiseledCoder/nikhilshirsath#21]
![screenshot from 2018-03-30 23 16 42](https://user-images.githubusercontent.com/10168623/38160311-6d072294-3470-11e8-9d2e-0282fd99bb64.png)

**Comment by chiseledCoder-zz** [comment]
Please check if this is fixed. it works perfectly fine in development environment.

**Comment by chiseledCoder-zz** [comment]
Close the issue if it is fixed

**Comment by Minal2179** [comment]
@chiseledCoder this is just an enhancement I pushing it to next release
