### ISSUE TITLE
Duplicate entry issue on creation of invoice

### ISSUE THREAD

**Issue by Minal2179** [chiseledCoder/nikhilshirsath#22]
![screenshot from 2018-03-30 23 18 21](https://user-images.githubusercontent.com/10168623/38160325-b2cb8c52-3470-11e8-8c4c-d2e1caa2c097.png)

**Comment by chiseledCoder-zz** [comment]
Code submitted in yesterday's release. Testing needed.

**Comment by Minal2179** [comment]
tested works fine
