### ISSUE TITLE
multivalue dict for service_fee_type

### ISSUE THREAD

**Issue by Minal2179** [chiseledCoder/nikhilshirsath#4]
![image](https://user-images.githubusercontent.com/10168623/37888638-59b2b6fa-307d-11e8-8ba9-38d80edaa48b.png)

**Comment by chiseledCoder-zz** [comment]
fixed:
`<input type="radio" id="oneTimeFeeRadio1" name="service_fee_type" value="One Time" class="custom-control-input" **checked="checked"**>`

**Comment by Minal2179** [comment]
This issue seems fixed, closing the issue
