### ISSUE TITLE
Record payment results in error page

### ISSUE THREAD

**Issue by Minal2179** [chiseledCoder/nikhilshirsath#6]
![image](https://user-images.githubusercontent.com/10168623/37888793-15cb48d4-307e-11e8-962b-de725c6ffca9.png)

**Comment by chiseledCoder-zz** [comment]
fixed
```
the_id = ("-").join(["RCPT", client_id, project_initials, "001"])
	try:
		get_receipt = Receipt.objects.get(receipt_id = the_id)
		if get_receipt:
			the_id = receipt_id_generator(invoice_id)
	except Receipt.DoesNotExist:
		pass
```

**Comment by Minal2179** [comment]
![screenshot from 2018-03-30 23 30 15](https://user-images.githubusercontent.com/10168623/38160422-56df2c30-3472-11e8-8e8f-c2093defad2c.png)
 getting this after clicking record payment in the dialogue box @chiseledCoder

**Comment by chiseledCoder-zz** [comment]
@Minal2179 This issue is fixed in yesterday's release.
